x = float(input("веддіть  дійсне число x :"))
print(" x =", x)
y = float(input("веддіть  дійсне число y :"))
print(" y =", y)
z = float(input("веддіть  дійсне число z :"))
print(" z =", z)
maxim = max(x, y, z )
print("Максимумом серед наведених чисел є (1) :",maxim)
minim = min(x, y, z )
print("Мінімумом серед наведених чисел є (2) :",minim)
maxim2=max(x+y+z, x*y*z)
print("Максимум 2 (3) = ",maxim2)